Fix Crystal Shard not growing
DeathCradle/Open-Terraria-API pull request #96
Opened 2022-11-04 20:07 UTC by sgkoishi

Fix Pryaxis/TShock#2796

The default value of `HardmodeTilePlaceEventArgs.Result` is null and will not `PlaceTile`.

2022-11-05 22:11 UTC, SignatureBeef requested changes

2022-11-05 22:11 UTC, SignatureBeef commented on OTAPI.Scripts/Mods/HookHardModeTilePlacement.Server.cs
> -                else if (args.Result == HardmodeTileUpdateResult.Continue)
I'm somewhat ok with this, but then the Result property needs to remove nullable since tri-state is no longer possible.

Instead can the result property be set to continue before invoking the event? This would then allow continue by default as it should have been, plus allows tri-state (for whatever reason, who knows what plugins come up with)

2022-11-06 00:58 UTC, sgkoishi commented on OTAPI.Scripts/Mods/HookHardModeTilePlacement.Server.cs
> -                else if (args.Result == HardmodeTileUpdateResult.Continue)
Keep both nullable and tri-state will have `null -> ContinueWithoutUpdate`... A rare path and not quite intuitive but everything else makes sense 🤣

2022-11-06 02:23 UTC, SignatureBeef approved these changes

2022-11-06 02:40 UTC, merged